name: pluto_menu_bar
description: A menu bar for flutter. You can add as many submenus as you want, and you can change the default style.
version: 1.0.0-nullsafety.0
homepage: https://bosskmk.github.io
repository: https://github.com/bosskmk/pluto_menu_bar

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety
